version: "3.9"

services:
  go-app:
    container_name: go-app
    image: go-api-ranking-games
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: {}